alias cdeb='cd ~/easybroker'
alias cdpm='cd ~/easybroker/property_manager'
alias cdea='cd ~/easybroker/easyaviso'
alias pms='cdpm && bers'
alias pmj='cdpm && be rails jobs:work'
alias eas='cdea && bers'
alias mysqlpm='mysql -uroot -hmysql property_manager_development'