alias pjt='cd ~/pjt'

alias jsl='code ~/pjt/devops/jenkins-shared-libraries'
alias k8s-manifests='code ~/pjt/devops/k8s-manifests'

alias agenda='cd ~/pjt/agenda'
alias boletin-judicial='cd ~/pjt/boletin-judicial'
alias commons='cd ~/pjt/commons'
alias devops='cd ~/pjt/devops'
alias estadisticas='cd ~/pjt/estadisticas'
alias expediente-virtual='cd ~/pjt/expediente-virtual'
alias flipbook='cd ~/pjt/flipbook'
alias infraestructura='cd ~/pjt/infraestructura'
alias inicio-expedientes='cd ~/pjt/inicio-expedientes'
alias justicia-de-paz='cd ~/pjt/justicia-de-paz'
alias oga='cd ~/pjt/oga'
alias padron-electoral='cd ~/pjt/padron-electoral'
alias portal-del-sae-v2='cd ~/pjt/portal-del-sae-v2'
alias portal-del-sae='cd ~/pjt/portal-del-sae'
alias rrhh='cd ~/pjt/rrhh'
alias sistemas-no-jurisdiccionales='cd ~/pjt/sistemas-no-jurisdiccionales'
